image: gitpod/workspace-full
tasks:
    - init: yarn install && yarn build
      command: yarn start
    - command:  sh ./gitpod-setup.sh && npm start
      name: Set up script
ports:
  - port: 8080
    onOpen: open-browser

