image:
  file: .gitpod.Dockerfile
tasks:
  - init: yarn install
    command:  . ./gitpod-setup.sh && netlify dev
    name: Setup script
ports:
  - port: 8888 # Webpack dev server
    onOpen: ignore
  - port: 8080 # Application
    onOpen: open-browser
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false
