image: gitpod/workspace-full
tasks:
  - init: yarn install
    command:  . ./gitpod-setup.sh && yarn start:dev
    name: Setup script
ports:
  - port: 34567
    onOpen: ignore
  - port: 8080-8081
    onOpen: ignore
  - port: 8080
    onOpen: open-browser
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false
