[build]
  publish = "dist"
  command = "npm run build"

[template.environment]
  ASTRA_DB_USERNAME = "REPLACE ME"
  ASTRA_DB_PASSWORD = "REPLACE ME"
  ASTRA_DB_KEYSPACE = "REPLACE ME"
  ASTRA_ENDPOINT = "REPLACE ME"
