[build]
  publish = "dist"
  command = "npm run build"

[template.environment]
  ASTRA_DB_USERNAME = "Your Astra DB Username"
  ASTRA_DB_PASSWORD = "Your Astra DB Password"
  ASTRA_DB_KEYSPACE = "Your Astra DB Keyspace"
  ASTRA_ENDPOINT = "Your Astra DB Endpoint"
